# Generated by Django 5.0.1 on 2026-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password_reset_required',
            field=models.BooleanField(default=True, help_text='Set to True when admin resets password', verbose_name='Password Reset Required'),
        ),
    ]
