# Generated by Django 5.0.1 on 2026-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_announcement_event_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Child Name (Tamil)'),
        ),
        migrations.AddField(
            model_name='member',
            name='address_ta',
            field=models.TextField(blank=True, default='', verbose_name='Address (Tamil)'),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Father's Name (Tamil)"),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Mother's Name (Tamil)"),
        ),
        migrations.AddField(
            model_name='member',
            name='name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Member Name (Tamil)'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Spouse's Name (Tamil)"),
        ),
    ]
