# Generated by Django 5.0.1 on 2026-07-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_taxmaster_child_marital_status_membertax_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxmaster',
            name='generated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Generated', 'Generated')], default='Open', max_length=20),
        ),
    ]
