# Generated by Django 5.0.1 on 2026-07-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accounthead_account_type_and_more'),
        ('members', '0010_taxmaster_generated_date_taxmaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxmaster',
            name='account_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_events', to='accounting.accounthead', verbose_name='Linked Account Head'),
        ),
    ]
