# Generated by Django 5.0.1 on 2026-07-14 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_trustaccount_family_member'),
        ('members', '0011_taxmaster_account_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fallback_father_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fallback Father Name (English)'),
        ),
        migrations.AddField(
            model_name='member',
            name='fallback_father_name_ta',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Fallback Father Name (Tamil)'),
        ),
        migrations.AddField(
            model_name='member',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Deceased / Expired'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_family_head',
            field=models.BooleanField(default=False, verbose_name='Family Head'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], default='Unmarried', max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='member',
            name='father_name_ta',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="Father's Name (Tamil)"),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
