# Generated by Django 5.0.1 on 2026-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_fallback_father_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reference_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Reference ID'),
        ),
    ]
