# Generated by Django 5.0.1 on 2026-07-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pending_update',
            field=models.JSONField(blank=True, null=True, verbose_name='Pending Profile Update'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_update_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='None', max_length=20, verbose_name='Profile Update Status'),
        ),
    ]
