# Generated by Django 5.0.1 on 2026-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_pending_update_member_profile_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fallback_father_name_en',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fallback_father_name_ta',
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
