# Generated by Django 5.0.1 on 2026-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_member_fallback_father_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City / Town'),
        ),
        migrations.AddField(
            model_name='member',
            name='address_city_ta',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City / Town (Tamil)'),
        ),
        migrations.AddField(
            model_name='member',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Last year Balance Tax Amount'),
        ),
        migrations.AddField(
            model_name='member',
            name='tax_count',
            field=models.FloatField(default=1.0, verbose_name='Tax Count'),
        ),
    ]
