version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/kalingar_trust_db
      - JWT_SECRET_KEY=your-production-jwt-secret
      - SECRET_KEY=your-production-secret-key
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 app:app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=kalingar_trust_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: