# Generated by Django 5.0.1 on 2026-07-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthead',
            name='description_ta',
            field=models.TextField(blank=True, default='', verbose_name='Description (Tamil)'),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='name_ta',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Account Head Name (Tamil)'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='donor_name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Donor Name (Tamil)'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='paid_to_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Paid To (Tamil)'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='purpose_description_ta',
            field=models.TextField(blank=True, default='', verbose_name='Purpose/Description (Tamil)'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='purpose_ta',
            field=models.TextField(blank=True, default='', verbose_name='Purpose / Remarks (Tamil)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='name_ta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name (Tamil)'),
        ),
    ]
