# Generated by Django 5.0.1 on 2026-07-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_tamil_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Credit', 'Credit')], max_length=20),
        ),
    ]
