# Generated by Django 5.0.1 on 2026-07-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accounttransaction_payment_mode'),
        ('members', '0010_taxmaster_generated_date_taxmaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthead',
            name='account_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Revenue', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='tax_event',
            field=models.ForeignKey(blank=True, help_text='Link to the tax event this transaction relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_transactions', to='members.taxmaster'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10),
        ),
    ]
