# Generated by Django 5.0.1 on 2026-07-13 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def remap_head_types(apps, schema_editor):
    AccountHead = apps.get_model('accounting', 'AccountHead')
    AccountHead.objects.filter(head_type__in=['Event', 'Recurring']).update(head_type='Kodai')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accounthead_account_type_and_more'),
        ('members', '0011_taxmaster_account_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remap_head_types),
        migrations.AddField(
            model_name='accounttransaction',
            name='commodity_type',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Other', 'Other')], default='', max_length=20, verbose_name='Commodity Type'),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='head_type',
            field=models.CharField(blank=True, choices=[('Kodai', 'Kodai'), ('General', 'General')], default='', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Credit', 'Credit'), ('Commodities', 'Commodities')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrustAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Commodities', 'Commodities')], max_length=20, verbose_name='Account Type')),
                ('associated_entity_type', models.CharField(choices=[('Trust_Direct', 'Trust Direct'), ('Member', 'Member'), ('Member_Family', 'Member Family')], max_length=20, verbose_name='Associated Entity Type')),
                ('account_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Bank Name')),
                ('branch_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Branch Name')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('deactivated_date', models.DateTimeField(blank=True, null=True, verbose_name='Deactivated Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trust_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_accounts', to='members.child', verbose_name='Custodian Family Member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_accounts', to='members.member', verbose_name='Custodian Member')),
            ],
            options={
                'verbose_name': 'Trust Account',
                'verbose_name_plural': 'Trust Accounts',
                'ordering': ['account_name'],
            },
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='trust_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.trustaccount', verbose_name='Trust Account'),
        ),
    ]
