# Generated by Django 5.0.1 on 2026-07-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accounttransaction_commodity_type_and_more'),
        ('members', '0011_taxmaster_account_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustaccount',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_trust_accounts', to='members.member', verbose_name='Custodian Family Member'),
        ),
    ]
